# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground = "#A8AFA6"
background = "#101411"
dim_foreground = "#8A928B"
bright_foreground = "#c3cdc0"

[colors.cursor]
text = "#101411"
cursor = "#A8AFA6"

[colors.vi_mode_cursor]
text = "#101411"
cursor = "#A8AFA6"

[colors.search.matches]
foreground = "#A8AFA6"
background = "#1F2624"

[colors.search.focused_match]
foreground = "#876f7f"
background = "#241d21"

[colors.selection]
text = "#A8AFA6"
background = "#241d21"

[colors.hints.start]
foreground = "#8A928B"
background = "#1D2320"

[colors.hints.end]
foreground = "#8A928B"
background = "#1D2320"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#A8AFA6"
background = "#1D2320"

[colors.normal]
black = "#101411"
red = "#9A6B6B"
green = "#859270"
yellow = "#A69966"
blue = "#8A8493"
magenta = "#876f7f"
cyan = "#7F9476"
white = "#A8AFA6"

[colors.bright]
black = "#6F7B6F"
red = "#B08585"
green = "#99A888"
yellow = "#C6B67E"
blue = "#A39DAC"
magenta = "#947e8d"
cyan = "#9AAB90"
white = "#c3cdc0"

[colors.dim]
black = "#101411"
red = "#9A6B6B"
green = "#859270"
yellow = "#A69966"
blue = "#8A8493"
magenta = "#876f7f"
cyan = "#7F9476"
white = "#8A928B"
